### ISSUE TITLE
Default environment starts with a dot: `.scipion3env`

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-installer#13]
I have not found any naming conventions, but I have not seen it before. Looks like a typo

**Comment by pconesa** [comment]
It's not a typo. The installer is sharing the name for both virtualenv and conda. The reason for the dot is:

hide the folder when going for a virtualenv installation.
Conda doesn't mind the name. 
keeping the same name regardless going for conda or virtualenv.
