### ISSUE TITLE
Workaround for installing on machine with < 4 mpi slots

### ISSUE THREAD

**Issue by mcianfrocco** [scipion-em/scipion-installer#20]
Hello - 

I'm trying to install scipion / XMIPP into a singularity container. To do this, I am installing everything from my home PC (Mac) on which I have sudo privileges. 

Everything goes fine until the MPI testing step. In short, it fails because it only finds 1 CPU for the MPI testing step: 

mpirun -np 4 --allow-run-as-root echo '    > This sentence should be printed 4 times if mpi runs fine.'
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4
slots that were requested by the application:

  echo

Either request fewer slots for your application, or make more slots
available for use.

Is there an 'easy' way to get around this? I'm not exactly sure which library it is pulling from. If I knew, I could update the mpirun test command to include --oversubscribe, unless there is another way around this test. 

I should say that this container will be run eventually on a computing cluster resource, not on my home PC. 

Thank you,
Mike

**Comment by pconesa** [comment]
Hi Mike, is only now I'm aware of this issue. Apologies. Is it still relevant?
As far as I know this is a mpi test. It work for us as long as you have 4 CPUs. Maybe the container hade less cores?

**Comment by azazellochg** [comment]
Currently, in xmipp 3.20.07 ./xmipp script requires 2 cpus (I guess was changed from 4), but --oversubscribe is still missing.

**Comment by mcianfrocco** [comment]
Hi @pconesa - thanks for checking in. I found a workaround by setting up a virtual machine with 4 CPUs on my laptop even though it only has two CPUs. This satisfied the MPI test. 

In the future, it would be an appreciated option. 

Mike

**Comment by pconesa** [comment]
Thanks @mcianfrocco . Please make anote @DStrelak , @dmaluenda

**Comment by DStrelak** [comment]
See also https://github.com/I2PC/xmipp/issues/306
