### ISSUE TITLE
Installer is ignoring the targed directory

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-installer#27]
Expected behavior:
```
(base) ~/work$ ls
scipion_release
(base) ~/work$ python -m scipioninstaller ~/work/scipion_devel -conda -n scipion3_devel -dev -j 8
``` 
results in all scipion and xmipp files (except, of course, the conda environment) will be located in the ~/work/scipion_devel folder

Actual behavior:
```
(base) ~/work$ python -m scipioninstaller ~/work/scipion_devel -conda -n scipion3_devel -dev -j 8
...
(base) ~/work$ ls
scipion-app  scipion_devel  scipion-em  scipion-pyworkflow  scipion_release  software  xmipp-bundle
```
i.e. the current directory is used to checkout all repositories (and links are added to the scipion_devel folder)

**Comment by azazellochg** [comment]
this is fixed
