### ISSUE TITLE
Error after adding new plugins

### ISSUE THREAD

**Issue by ChrisSKL** [scipion-em/scipion-installer#37]
Hi team,

We have successfully installed Scipion3 (but not yet to start a project). After importing a workflow, I found that some of the plugins are missing.
After installing those plugins, I found that I could not run Scipion3 again, with the error message below.

----------

~/.local/scipion/3/config$ scipion3
Scipion v3.3.1 - Eugenius
Failed to read settings. The reported error was:
  Source contains parsing errors: '/beebylab/home/chris/.local/scipion/3/config/hosts.conf'
	[line 12]: '}\n'
Review /beebylab/home/chris/.local/scipion/3/config/hosts.conf and run again.

--------
I have checked that [line 12] and it is the same as the template in the website. Would you advise?

Thank you very much.

Chris

**Comment by azazellochg** [comment]
Hi @ChrisSKL I believe you are missing a space before '}'.
Apologies for the very late reply, this repo is not monitored... I suggest opening issues at https://github.com/scipion-em/scipion-pyworkflow/issues/new

**Comment by pconesa** [comment]
I'm closing this. Feel free to reopen in case I'm wrong.
