### ISSUE TITLE
tkinter dependency fails

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-installer#4]
Hi,

   I need to install tkinter by hand in order to use this installer

sudo apt-get install python3-tk 

you may add the command to the instalation procedure

**Comment by azazellochg** [comment]
where is it used? I assumed this installer does not do anything except git pull / pip install

**Comment by delarosatrevin** [comment]
Yes, apt will only work for debian/ubuntu systems.

**Comment by azazellochg** [comment]
why do you need it in the system and not in venv (no sudo required)?

**Comment by pconesa** [comment]
any "universal" way to do this?

**Comment by pconesa** [comment]
we will document it as a dependency in the installation documentation.
